apiVersion: v1
kind: Service
metadata:
  name: image-organizer-service
spec:
  selector:
    app: image-organizer
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8080  # Port inside the container, adjust as needed
  type: ClusterIP  # Use "NodePort" or "LoadBalancer" if you want external access
